name: Build module

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Get version
        run: |
          VERSION=$(gh release view --repo JoeBlakeB/ttf-twemoji --json tagName --jq .tagName)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Download release assets
        uses: robinraju/release-downloader@v1
        with:
          repository: JoeBlakeB/ttf-twemoji
          tag: ${{ env.VERSION }}
          fileName: Twemoji-${{ env.VERSION }}.ttf
          out-file-path: system/fonts

      - name: Bump
        run: |
          version_code=$(echo ${{ env.VERSION }} | tr -d '.')

          sed -i "s/^version=.*/version=${{ env.VERSION }}/" module.prop
          sed -i "s/^versionCode=.*/versionCode=$version_code/" module.prop
          jq --arg ver "${{ env.VERSION }}" \
             --arg verCode "$version_code" \
             '.version = $ver | .versionCode = ($verCode | tonumber)' update.json > update.json.tmp && mv update.json.tmp update.json
          echo "Bump to ${{ env.VERSION }}" > changelog.txt

      - name: Create artifact
        run: |
          mv system/fonts/Twemoji-${{ env.VERSION }}.ttf system/fonts/NotoColorEmoji.ttf
          zip -r ttf-twemoji-ksu.zip system module.prop

      - name: Commit
        uses: EndBug/add-and-commit@v10
        with:
          add: "module.prop update.json changelog.txt"
          author_name: "github-actions[bot]"
          author_email: "github-actions[bot]@users.noreply.github.com"
          message: "Bump to ${{ env.VERSION }}"

      - name: Upload artifact to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ttf-twemoji-ksu.zip
          asset_name: ttf-twemoji-ksu.zip
          tag: ${{ env.VERSION }}
          overwrite: true
          release_name: ttf-twemoji-ksu ${{ env.VERSION }}
